# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-demo.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erpc-demo.proto\x12\nRPCDemoPkg\x1a\x1bgoogle/protobuf/empty.proto\" \n\nMultCoords\x12\x12\n\x06values\x18\x01 \x03(\x01\x42\x02\x10\x01\"<\n\x0bImageResult\x12\x0e\n\x06\x62\x36\x34img\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r2\x91\x01\n\x07RPCDemo\x12\x41\n\rGetMultCoords\x12\x16.google.protobuf.Empty\x1a\x16.RPCDemoPkg.MultCoords\"\x00\x12\x43\n\x0eGetImageResult\x12\x16.google.protobuf.Empty\x1a\x17.RPCDemoPkg.ImageResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MULTCOORDS'].fields_by_name['values']._options = None
  _globals['_MULTCOORDS'].fields_by_name['values']._serialized_options = b'\020\001'
  _globals['_MULTCOORDS']._serialized_start=59
  _globals['_MULTCOORDS']._serialized_end=91
  _globals['_IMAGERESULT']._serialized_start=93
  _globals['_IMAGERESULT']._serialized_end=153
  _globals['_RPCDEMO']._serialized_start=156
  _globals['_RPCDEMO']._serialized_end=301
# @@protoc_insertion_point(module_scope)
